### ISSUE TITLE
关于昨天发的docker自建回复延迟大

### ISSUE THREAD

**Issue by Plus-xu** [Nekohy/pieces-os#11]
今天测试了好久，终于找到原因了
使用同一个服务器，如果直接用http访问，速度很快，但是如果用NGINX反代并加证书，用https访问，会导致回复延迟暴增到8-10s以上
同demo一样，域名用cloudflare dns解析

**Comment by 2328760190** [comment]
emmm，所以呢

**Comment by Plus-xu** [comment]
> emmm，所以呢

我这个像是什么原因导致的呢？..我用美国和日本的服务器测试都这样

**Comment by nekohy** [comment]
建议自查，这跟项目自身无关
