### ISSUE TITLE
Claude系列 nextchat用不了

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [Nekohy/pieces-os#12]
自定义模型将@替换为-,出现`{
  "status": 401,
  "error": "Unauthorized: Missing or invalid Authorization header"
}`
用公共服务网址试了，状况没有变化。
nextchat版本是2.15.6，其余的正常。
不知道原因，谢谢。

**Comment by nekohy** [comment]
请填写自定义模型，而不是直接用选项里的，例如Claude-xxx@Pieces，你那样调用的是Cluade接口
