### ISSUE TITLE
貌似不能用了，返回404

### ISSUE THREAD

**Issue by 3377** [Nekohy/pieces-os#14]
还没爽一天。。。快是真的快

**Comment by nekohy** [comment]
等我修（

**Comment by 3377** [comment]
啊，你竟然还没睡，是官方调整了吗？另外这个max token是多少啊，我发现超过8000就出错了。

**Comment by nekohy** [comment]
看cloud.json，我一般昼伏夜出

**Comment by nekohy** [comment]
> 啊，你竟然还没睡，是官方调整了吗？另外这个max token是多少啊，我发现超过8000就出错了。

proto没变，但是对面直接截断流了，但是我一个朋友部署的Vercel又没问题，奇怪

**Comment by 3377** [comment]
> > 啊，你竟然还没睡，是官方调整了吗？另外这个max token是多少啊，我发现超过8000就出错了。
> 
> proto没变，但是对面直接截断流了，但是我一个朋友部署的Vercel又没问题，奇怪

我去部署了个vercel，也是报404
![image](https://github.com/user-attachments/assets/172c2b9f-91f3-4ab2-8e8b-2dd9be65bd05)

**Comment by 3377** [comment]
开始怀疑是ip被ban，用vps也测试了下，结果一样。

**Comment by nekohy** [comment]
UA问题，Javascript的库没法改UA，在找解决方法 https://github.com/grpc/grpc-node/pull/2728

**Comment by gjw0813** [comment]
> UA问题，Javascript的库没法改UA，在找解决方法 [grpc/grpc-node#2728](https://github.com/grpc/grpc-node/pull/2728)

正确的UA应该是啥？ 是不是可以patch-package硬编码grpc-node的UA

**Comment by mo-qc** [comment]
我的返回到没问题，就是不能输出结果

**Comment by nekohy** [comment]
Finish https://github.com/Nekohy/pieces-os/commit/bde8b931aaec4b198aae35c434e3c2371de73b0e
