### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 2328760190** [Nekohy/pieces-os#17]
在nextchat内请求gemini-1.5-pro，询问特定问题，例如:你叫什么名字
返回内容会多一个assistant:
可叠加

**Comment by nekohy** [comment]
![{C945BA96-2EFD-4516-8FA2-A3A69B1206A7}](https://github.com/user-attachments/assets/d46ccc8c-16bd-48b4-b551-9224239fd809)
请换其他软件而不是让我主动适配某个软件，wont fix
