### ISSUE TITLE
用Vercel部署的，跑过一段时间后就开始504了

### ISSUE THREAD

**Issue by jason-lee-x** [Nekohy/pieces-os#18]
![image](https://github.com/user-attachments/assets/dccdd78e-14f7-448f-8e3d-40141cbbf241)

这个是被封IP了吗？所有模型都不可用。

**Comment by nekohy** [comment]
我项目不可能抛出任何带有HTML的界面（

**Comment by nekohy** [comment]
你应该优先排除个人Vercel的问题

**Comment by jason-lee-x** [comment]
> 你应该优先排除个人Vercel的问题

Vercel应该没问题，一键部署的，配置没啥需要改的。

如果我输入一个错误的Bearer Token，他会很快返回。

` 
{
    "status": 401,
    "error": "Unauthorized: Missing or invalid Authorization header"
}
`

如果我输出正确的Bearer Token，他则会请求超过60秒，最后获得一个Bad Gateway。

**Comment by nekohy** [comment]
![{DCAA80EC-24A3-4E4A-9591-7F7F0372D4C1}](https://github.com/user-attachments/assets/1d6bc2c8-f924-45aa-aad5-71677a3ddf11)
无法复现，

**Comment by Nekohy** [comment]
不为任何非个人使用的大流量行为做任何技术支持
