### ISSUE TITLE
docker会莫名巧妙的崩了

### ISSUE THREAD

**Issue by Ze-raphine** [Nekohy/pieces-os#5]
![image](https://github.com/user-attachments/assets/8ff7c8bb-e8ea-49bf-8341-03761b0f3a5c)
类似这样，docker会莫名奇妙的崩掉，只能重启

**Comment by 2328760190** [comment]
已合并主代码并重新打包，可以重新拉取latest试试

**Comment by 2328760190** [comment]
![Screenshot_20241102_215708](https://github.com/user-attachments/assets/50044c9a-78ec-4484-9f76-a778d9012aae)

**Comment by nekohy** [comment]
我不负责docker这块（

**Comment by nekohy** [comment]
还存在问题吗

**Comment by Ze-raphine** [comment]
重新拉了镜像，还是偶尔会崩

**Comment by nekohy** [comment]
> 重新拉了镜像，还是偶尔会崩

你单跑js试下

**Comment by nekohy** [comment]
这个docker不是我维护的（看情况修吧

**Comment by 2328760190** [comment]
我拉镜像能正常用啊，demo2就是docker跑的

**Comment by 2328760190** [comment]
初步推断不开黄车就不会崩溃，demo2崩溃2次，日志差不多
[olympic-staci-pieces-os_2024-11-03T04_51_11.361Z.txt](https://github.com/user-attachments/files/17609407/olympic-staci-pieces-os_2024-11-03T04_51_11.361Z.txt)

**Comment by nekohy** [comment]
> 初步推断不开黄车就不会崩溃，demo2崩溃2次，日志差不多 [olympic-staci-pieces-os_2024-11-03T04_51_11.361Z.txt](https://github.com/user-attachments/files/17609407/olympic-staci-pieces-os_2024-11-03T04_51_11.361Z.txt)

6，怎么还有这种人

**Comment by 2328760190** [comment]
已完成自动重启，拉取latest即可，点star⭐
