### ISSUE TITLE
这个部分能不能也变成 claude-3.5-sonnet-20240620

### ISSUE THREAD

**Issue by shuwu-ui** [Nekohy/pieces-os#6]
<img width="463" alt="image" src="https://github.com/user-attachments/assets/3d87ff36-7abe-4121-bf8c-d6fd9d701b05">
这个部分能不能也变成 claude-3.5-sonnet-20240620

**Comment by nekohy** [comment]
它似乎没有什么必要吧，想加也不难

**Comment by nekohy** [comment]
因为单纯为了兼容 Nextchat 就额外加了一个转换

**Comment by shuwu-ui** [comment]
> 它似乎没有什么必要吧，想加也不难

可以加的话麻烦有时间加一下吧 佬

**Comment by nekohy** [comment]
> > 它似乎没有什么必要吧，想加也不难
> 
> 可以加的话麻烦有时间加一下吧 佬

它有什么应用场景吗（？，有的话且用处很大的话我考虑下

**Comment by shuwu-ui** [comment]
> > > 它似乎没有什么必要吧，想加也不难
> > 
> > 
> > 可以加的话麻烦有时间加一下吧 佬
> 
> 它有什么应用场景吗（？，有的话且用处很大的话我考虑下

我有部分项目是检测回复的模型名称的去进行文件写入  因为是写死了的   所以要改动起来非常的繁琐

**Comment by nekohy** [comment]
> > > > 它似乎没有什么必要吧，想加也不难
> > > 
> > > 
> > > 可以加的话麻烦有时间加一下吧 佬
> > 
> > 
> > 它有什么应用场景吗（？，有的话且用处很大的话我考虑下
> 
> 我有部分项目是检测回复的模型名称的去进行文件写入 因为是写死了的 所以要改动起来非常的繁琐

行吧，等我下

**Comment by nekohy** [comment]
> > > > 它似乎没有什么必要吧，想加也不难
> > > 
> > > 
> > > 可以加的话麻烦有时间加一下吧 佬
> > 
> > 
> > 它有什么应用场景吗（？，有的话且用处很大的话我考虑下
> 
> 我有部分项目是检测回复的模型名称的去进行文件写入 因为是写死了的 所以要改动起来非常的繁琐

不对啊 你可以直接带@回复的（除了Nextchat都可以

**Comment by shuwu-ui** [comment]
就是把回复带@的修改成和输入一样的@变成-
然后拉的新文件，运行流之后还是有之前的错误
<img width="570" alt="image" src="https://github.com/user-attachments/assets/4a0a382d-1c88-4892-b4c6-49f76fb82db7">

**Comment by shuwu-ui** [comment]
> 就是把回复带@的修改成和输入一样的@变成- 然后拉的新文件，运行流之后还是有之前的错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/152254394/382487497-4a0a382d-1c88-4892-b4c6-49f76fb82db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjUyNjMsIm5iZiI6MTczMDU2NDk2MywicGF0aCI6Ii8xNTIyNTQzOTQvMzgyNDg3NDk3LTRhMGEzODJkLTFjODgtNDg5Mi1iNGM2LTQ5Zjc2ZmI4MmRiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNjI5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTkzNWNiNmJkY2Q1ZmE2NzA4YTk1MzBkNzcwNWYyYTdmMjIxNWI5ZDI0Y2NmMmUyZWZjYWNjZWYzZTQzYmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VADxu-3L-yAtDR092vJFSusEFgEOIaYFiICjpaRrki8">

我电脑的 node 版本是 22 的

**Comment by nekohy** [comment]
> > 就是把回复带@的修改成和输入一样的@变成- 然后拉的新文件，运行流之后还是有之前的错误 <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/152254394/382487497-4a0a382d-1c88-4892-b4c6-49f76fb82db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjUyNjMsIm5iZiI6MTczMDU2NDk2MywicGF0aCI6Ii8xNTIyNTQzOTQvMzgyNDg3NDk3LTRhMGEzODJkLTFjODgtNDg5Mi1iNGM2LTQ5Zjc2ZmI4MmRiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNjI5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTkzNWNiNmJkY2Q1ZmE2NzA4YTk1MzBkNzcwNWYyYTdmMjIxNWI5ZDI0Y2NmMmUyZWZjYWNjZWYzZTQzYmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VADxu-3L-yAtDR092vJFSusEFgEOIaYFiICjpaRrki8">
> 
> 我电脑的 node 版本是 22 的

完成，https://github.com/Nekohy/pieces-os/commit/2b9deaa9c43b5d25fd4e2dcedce4f6fce52dd044
