### ISSUE TITLE
回复延迟大

### ISSUE THREAD

**Issue by Plus-xu** [Nekohy/pieces-os#7]
docker自建与项目demo（https://pieces.464888.xyz） 回复速度差异非常大，都使用cloudflare代理网站，网络延迟基本一致，但是项目demo首字回复1s，全部回复用时大概3-7s，而自建的docker版首字需要5-10秒，全部回复用时需要10s以上

**Comment by shuwu-ui** [comment]
<img width="470" alt="image" src="https://github.com/user-attachments/assets/c69c28a1-169b-465b-be51-77fafaa503ec">

我在本地跑沉浸式大概在 1-3s 完成一个对话 不清楚你那个是啥问题

**Comment by 2328760190** [comment]
demo也是docker跑的，可能是你自建用的服务器延迟高，demo的部署地址是美国的，实测我香港线路优化服务器首字在1.5秒左右
